config/routes.rb
Rails.application.routes.draw do
  root to: 'budget#show'
  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' }

  resources :reconciliations, path: :reconcile, only: [:index, :new, :create]
  resource :budget, controller: :budget
  resources :buckets, except: :index do
    get :reconcile, on: :collection
  end

  namespace :transaction do
    resources :expenses
    resources :incomes
  end

  namespace :bank do
    resources :logins
    resources :accounts
  end

  namespace :api do
    namespace :int do
      resources :buckets, except: :new
    end
  end

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'michaeldawson' && password == 'sidekiq is fun'
  end
  mount Sidekiq::Web => '/sidekiq'
end

app/models/bucket.rb
class Bucket < ApplicationRecord
  acts_as_paranoid

  attribute :amount, MoneyType.new
  attribute :balance, MoneyType.new

  belongs_to :budget, inverse_of: :buckets
  has_many :transactions, inverse_of: :bucket
  has_many :expenses, -> { where(type: 'Transaction::Expense') }, class_name: 'Transaction::Expense'
  has_many :pay_day_transactions, -> { where(type: 'Transaction::Income') }, class_name: 'Transaction'
  has_many :transaction_patterns, inverse_of: :bucket

  validates :budget, presence: true
  validates :amount, presence: true
  validates :balance, presence: true
  validate :amount_not_negative # Can't use a numericality validation as it's sometimes cast as '$x.xx'
  def amount_not_negative
    errors.add(:amount, "can't be negative") if amount.negative?
  end

  scope :uncategorised, -> { where(default: true) }
  scope :categorised, -> { where(default: false) }
end

app/controllers/api/int/buckets_controller.rb
module API
  module Int
    class BucketsController < BaseController
      def index
        render json: buckets
      end

      def create
        if bucket.save
          render json: bucket
        else
          render json: bucket.errors
        end
      end

      def update
        bucket.update(bucket_params)
        head :ok
      end

      def destroy
        bucket.destroy
        render json: bucket
      end

      private

      def buckets
        return Bucket.none unless current_budget
        @buckets ||= current_budget.buckets
      end

      def bucket
        @bucket ||= current_budget.buckets.find(params[:id]) if params.key?(:id)
        @bucket ||= current_budget.buckets.new(bucket_params)
      end

      def bucket_params
        params.require(:bucket).permit(:id, :name, :amount) if params.key?(:bucket)
      end
    end
  end
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_current_budget

  def update
    if bucket.update(bucket_attributes)
      flash[:notice] = 'Bucket was updated'
      redirect_to bucket
    else
      flash[:error] = "Sorry, that didn't work"
      render 'edit'
    end
  end

  def reconcile
    @bucket = current_budget.default_bucket
    render 'show'
  end

  private

  helper_method def bucket
    @bucket ||= Bucket.find(params[:id])
  end

  helper_method def budget_report
    @budget_report ||= Report::BudgetReport.new(current_budget, current_budget.current_cycle)
  end

  def bucket_attributes
    params.require(:bucket).permit(:name, :amount, :balance)
  end

  helper_method def transaction
    @transaction ||= Transaction::Expense.new(effective_date: Time.current.to_date)
  end
end

app/views/buckets/_pie_chart.html.haml
- chart_data = budget_report.expenses_by_bucket.map { |k, v| { label: k.name, data: v.dollars} }
#accountsPieChart.plotPieChart{ data: { chart: chart_data.to_json } }

app/views/buckets/edit.html.haml
- content_for :page_title, "Edit #{bucket.name}"

.container
  %h3.bucket Editing #{bucket.name}
  = simple_form_for(bucket) do |form|
    = form.hidden_field :id, value: bucket.id
    = form.input :name
    = form.input :amount
    = form.input :balance
    = form.submit 'Save'

app/views/buckets/show.html.haml
- reconciling = bucket.default?
- content_for :page_title, (reconciling ? 'Reconcile' : bucket.name)

.container
  - if reconciling
    %h3 Reconcile
  - else
    %h3.bucket #{bucket.name} #{bucket.balance} available
  - unless bucket.default
    = link_to 'Edit', edit_bucket_path(bucket)
    %hr
    %h4 New transaction
    = render 'transactions/form'
    %hr

  %table.table.table-striped.table-hover.bucket-transactions
    %thead
      %th Date
      %th.hidden-xs Source
      %th Description
      %th Amount
      %th
    %tbody
      - bucket.expenses.order(effective_date: :desc).each do |transaction|
        %tr
          %td= transaction.effective_date.strftime('%d/%m/%Y')
          %td.hidden-xs= transaction.source
          %td
            - description = transaction.description.truncate(45)
            - if transaction.bucket.default
              = link_to description, transaction
            - else
              = description
          %td= transaction.amount
          %td
            = link_to [:edit, transaction] do
              %i.ion-edit